### ISSUE TITLE
80 port instead of 3000

### ISSUE THREAD

**Issue by Sallaxer** [clockworklabs/SpacetimeDB#203]
In release 0.6.1, the server starts on port 80, not 3000 as specified in the instructions

![image](https://github.com/clockworklabs/SpacetimeDB/assets/91719856/f5cae1e6-4213-48e2-94d4-a61ead036af6)

**Comment by Sallaxer** [comment]
I think because of this https://github.com/clockworklabs/SpacetimeDB/blob/master/crates/standalone/src/subcommands/start.rs#L27
But it turns out that the argument `-p 3000:3000` is useless

**Comment by Sallaxer** [comment]
And I'd also add a help call command to the start splash screen (or make the alias to just `spacetimedb help`), since `spacetimedb help start` is not obvious

**Comment by jdetter** [comment]
@Sallaxer Sorry for getting back to you so late on this, the `0.0.0.0:80` message at the end there is kind of a scam because its running on port 80 in the docker but then we're exposing it as `3000`. And you're right that the command `-p 3000:3000` is doing nothing, we will fix that in our documentation and on the installation page, I'm not sure how we missed that 😦 

Thank you for the feedback!

**Comment by jdetter** [comment]
We have addressed this issue in the README for this repository, and the installation instructions for https://spacetimedb.com . The new command is:
```bash
docker run --rm --pull always -p 3000:80 clockworklabs/spacetimedb start
```

Thank you for reporting this issue, I'm closing it now as resolved!
