### ISSUE TITLE
Investigate publish error with v1.0.0-rc2 and Pogly's C# module

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#2060]
@rreverser looks like there's a bug on the `release/v1.0.0-rc2` branch. I can help you reproduce. It could be an issue with my cherry-picking, but either way let's work on a fix first thing Monday.

To reproduce publish https://github.com/PoglyApp/pogly-standalone/tree/1.0.0-rewrite/server using https://github.com/clockworklabs/SpacetimeDB/pull/2052

Let's add a new regression test for this one as well once we figure it out. It didn't get caught in our automated testing

**Comment by RReverser** [comment]
From a quick glance, it looks like the issue that was fixed by https://github.com/clockworklabs/SpacetimeDB/pull/1987.

The publishing in this case invokes some irrelevant reducer instead of "init" one, and then fails due to argument mismatch. It is similar to the bug I fixed there, with wrong reducers being called.

Can you confirm if that PR was cherry-picked?

**Comment by bfops** [comment]
This indeed fixed the issue.
